version: "3.7"
services:
  ex1:
    image: decima/mds-activity-2:ex-1
    build:
      context: ./exercice-1
  ex2:
    image: decima/mds-activity-2:ex-2
    build:
      context: ./exercice-2
    command: "Henri"
  ex3:
    image: decima/mds-activity-2:ex-3
    build:
      context: ./exercice-3
    volumes:
      - ./motd.txt:/data/motd.txt
  ex4:
    image: decima/mds-activity-2:ex-4
    build:
      context: ./exercice-4
    ports:
      - 8000:9000
  ex5:
    image: decima/mds-activity-2:ex-5
    build:
      context: ./exercice-5
    environment:
      HOST_AND_PORT: 0.0.0.0:9001
    ports:
      - 8001:9001
  ex6-server:
    image: decima/mds-activity-2:server
    build:
      context: ./exercice-6-server
    environment:
      HOST_AND_PORT: 0.0.0.0:9000
  ex6-client:
    image: decima/mds-activity-2:client
    build:
      context: ./exercice-6-client
    environment:
      SERVER: ex6-server:9000
